### ISSUE TITLE
Says i dont have enough resources when i have more than enough

### ISSUE THREAD

**Issue by CreditRoll** [Lanboost/TModLoader_LansHouseBuilder#1]
hey, so i was tryin to create a house with the house mod, and i had significantly more materials than needed for one house (34 platforms, 12 crafting benches and chairs, 68 torches, 239 wood, 634 walls, all wooden) and it told me that i cant pay for the house cost. thank you in advance :)

**Comment by Lanboost** [comment]
Yes, for now the torch itself is not actually what you need, and I have been working on fixing the behaviour and to give a good description of the error. You actually only need wood/or and stone and 1 gel (the torch is made with wood and gel) and not actually with a torch.

Some day the fix will be to use either a torch or gel+wood.. Leaving this open for now

**Comment by Lanboost** [comment]
With version 0.11.3 this now (hopefully) gives both descriptive error messages and now can take either wood+gel or torches

Closing this issue, thanks!
